services:
  mail-connector:
    build: ./mail-connector
    ports:
      - "5000:5000"
    # volumes:
      # - ./mail-data:/app/data
    environment:
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}