services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - mail_summarizer_net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - mail_summarizer_net

networks:
  mail_summarizer_net:
    driver: bridge
